### PR TITLE
Unique Ms values

### PR DESCRIPTION
**Pull request by samjrholt**

### CODE REVIEW

**Review by swapneelap — APPROVED** [review]
Looks good!

**Comment by lang-m** [comment]
@samjrholt Please merge when you have had a look.

**Comment by samjrholt** [comment]
@lang-m Currently an error for unique_with_accuracy with an input of an empty array. This occurs for a multisubregion case with no subregion overlap. The error stems from np.max. We could change it so that it returns an epmpty array when an empty array is supplied?

**Comment by samjrholt** [comment]
Looks good @lang-m

**Pull request merged**
